version: '3'
services:
  service-a:
    image: 'service-a'
    ports:
      - '8800:8800'
    networks:
      - msa-network
  zuul-api-gateway:
    image: 'api-gateway'
    ports:
      - '8888:8888'
    networks:
      - msa-network
networks:
  msa-network:

  